### ISSUE TITLE
Commented out deprecated method causes Task to be displayed as deprecated in IntelliJ IDEA

### ISSUE THREAD

**Issue by matejdro** [UM-LPM/EARS#10]
Inside `Task.java` there is a javadoc marked with deprecation that points to nothing (method that javadoc should point to is commented out):

https://github.com/UM-LPM/EARS/blob/master/src/org/um/feri/ears/problems/Task.java#L225

That causes IntelliJ IDEA IDE to think whole `Task` class is deprecated:

![image](https://user-images.githubusercontent.com/507922/31941111-dfe4c8ec-b8c0-11e7-958f-3f1edc60e831.png)

**Comment by Ravby** [comment]
The deprecated method has been removed. 8a5564e6acec1c61838858bfc96a7e8c766ac66b
