### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by kb2623** [UM-LPM/EARS#17]
I have problems building this project, because some tools do not recognize this project correctly. Please use some build tool like Gradle to ease the problem of project initialization and project building.

**Comment by Ravby** [comment]
Can you give some additional info about the problem? Maybe the exact exception that is being returned. It is also useful to know how the project is built, which tools are used and with which IDE.

**Comment by kb2623** [comment]
The main problem is that I have to use IDE to build your project, if your project had some build system I cud build the project inside a terminal.
