### ISSUE TITLE
org.jetbrains.kotlin.jvm version 2.1.0 is not supported on Gradle version 7.5.1

### ISSUE THREAD

**Issue by mitkonikov** [UM-LPM/EARS#27]
I had to update the Gradle version to 7.6.3 to fix the issue.

I mention @Ravby because you changed the plugin version in commit 97f6f508cccaa45430bb8c102256ea38df184400 which is not compatible with this older Gradle that the project was based on.

It could be the case that your IDE somehow exchanges the Gradle versions on the fly and thus it works for you. Anyhow, you should update the Gradle version in case you are using the Jetbrains' 2.1.0 Kotlin plugin version.

To fix it, I just changed the `distributionUrl` of the Gradle properties to:
```env
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-bin.zip
```

**Comment by Ravby** [comment]
The gradle version has been updated
