### ISSUE TITLE
Update single objective intervals for example in ProblemSphere

### ISSUE THREAD

**Issue by Mir1001** [UM-LPM/EARS#3]
upperLimit = new ArrayList<Double>(Collections.nCopies(numberOfDimensions, 200.0));
->upperLimit = new ArrayList<Double>(Collections.nCopies(numberOfDimensions, 100.0));

public ProblemSphere(int d) {
		super(d,0);
		
		lowerLimit = new ArrayList<Double>(Collections.nCopies(numberOfDimensions, -100.0));
		upperLimit = new ArrayList<Double>(Collections.nCopies(numberOfDimensions, 200.0));
		
		name = "Sphere";
	}

**Comment by Ravby** [comment]
Intervals for all singleobjective problems have been updated.
