### ISSUE TITLE
CPU Stop criteria for single run is not working!

### ISSUE THREAD

**Issue by Mir1001** [UM-LPM/EARS#5]
In case of:

public class Main4Run {

	public static void main(String[] args) {
		Task t = new Task(EnumStopCriteria.CPU_TIME, 5000, 1000, 0, 0.0001, new Sphere(5)); //run problem Sphere Dimension 5, 3000 evaluations
		RandomWalkAlgorithm test = new RandomWalkAlgorithm();
		try {
			System.out.println(test.execute(t)); //prints best result afrer 3000 runs
		} catch (StopCriteriaException e) {
			e.printStackTrace();
		}
	}
}
CPU Time is not working for single run!

**Comment by Ravby** [comment]
Initial time was not set.
Added startTimer to Task.
