### ISSUE TITLE
TaskComparator.compare throws NullPointerException

### ISSUE THREAD

**Issue by DKorosec** [UM-LPM/EARS#6]
When testing the example (from project readme) - MainBenchMarkTest - the program sometimes randomly crashed. This issue can be 100% reproduced if random seed at the beginning of main body is set to 3
( `Util.rnd.setSeed(3)` ).

**Comment by matejdro** [comment]
This also happens with seed `20`.

**Comment by Ravby** [comment]
Fixed problem when stop criteria reached in the initialization of TLBO. 537dba3ee109a8130d0a2803e6014e899f639197
